version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - 3001:3001
    depends_on:
      - frontend

  frontend:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/home/frontend/app'
      - '/home/frontend/app/node_modules'
    ports:
      - "3000:3000"
    # tty: true
    expose:
      - 3000

# networks: 
#   default: 
#     external: 
#       name: suvido-network
