version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/home/frontend/app'
      - '/home/frontend/app/node_modules'
    ports:
      - "3000:3000"
    tty: true
    expose:
      - 3000

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - frontend

networks: 
  default: 
    external: 
      name: suvido-network
