version: '3.7'

services:
  frontend:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/home/frontend/app'
      - '/home/frontend/app/node_modules'
    ports:
      - "9090:9090"
    tty: true
    expose:
      - 9090

networks: 
  default: 
    external: 
      name: suvido-network
